services:
  api:
    image: viet-tts:latest
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - viet-tts:latest
    restart: always
    container_name: viet-tts-service
    ports:
      - "8298:8298"
    
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    
    volumes:
      - ./pretrained-models:/app/pretrained-models
      - ./viettts:/app/viettts       
      - ./samples:/app/samples      
      - ./web:/app/web              

    command: python -m viettts.cli server --host 0.0.0.0 --port 8298
    
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=""

volumes:
  poetry-cache:
  pip-cache:
